// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PulsePitch.Data;

#nullable disable

namespace PulsePitchBackend.Migrations
{
    [DbContext(typeof(PulsePitchDbContext))]
    [Migration("20260201015657_AddTeamVisibilityAndApproval")]
    partial class AddTeamVisibilityAndApproval
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        },
                        new
                        {
                            Id = "e9b4c5a4-76c6-44b7-88fb-35a0228c9572",
                            Name = "Coach",
                            NormalizedName = "COACH"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3805d1a8-6902-4a96-9993-72d6fd05b02f",
                            Email = "admin@strator.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMfv15xMzPx0DpLeP4ItEdylHOfob3hxYoaECqwHjN/b7lp7KhPDJId3OSXwH5w9zA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "418bfd8f-06a1-4673-9dd6-0958868885b4",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0f96984-173a-4c58-9bfc-2ce608fef9ea",
                            Email = "john@doe.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEIQ4Hb84MNiJX6K+Pv5DRoaBF6l/XykjG9P+APG7LPsQdxh0LBQWcgblUUCPUJOSew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2587e05c-d075-47bc-af05-244633e9b6c0",
                            TwoFactorEnabled = false,
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6b63f3ba-5e6b-4e85-8021-894deb22f2d2",
                            Email = "jane@smith.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAELCeHxQUAgmYV51o2+AZYz36zvdSgKw+Rr7mT0Q+i955k0PFJKrG39VL7/8dW3jjZA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "e0207b01-1d4c-4178-9cd6-f36317ae8f9b",
                            TwoFactorEnabled = false,
                            UserName = "JaneSmith"
                        },
                        new
                        {
                            Id = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e0ee0275-bd95-4df8-ad11-d8ddac2add85",
                            Email = "alice@johnson.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPY4VWc6Xft8hQlLQvIZf3Y+tzEQ9H78YkcOzmhdNvshlaKaNijK2Ji+8uWFnuZ4ig==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "0e27bc78-46d6-40bd-8199-f72c1062440d",
                            TwoFactorEnabled = false,
                            UserName = "AliceJohnson"
                        },
                        new
                        {
                            Id = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "11314fae-75b4-4ff9-a7b8-a8e30db3ee99",
                            Email = "bob@williams.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJZkdb+JN+UDqRFpJRjmBFzzN20cIiy6wQFL3RZyoVgsfRBkmbmmcuvfu9hWaSQf/g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7e43c9fd-8913-457e-aff6-01f08c20e490",
                            TwoFactorEnabled = false,
                            UserName = "BobWilliams"
                        },
                        new
                        {
                            Id = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b37446b0-fe37-4a26-b400-9d496929a53e",
                            Email = "Eve@Davis.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEILpfQFBBuObfVP/GHYArAUIM49RfO069YfOHtD91mVSyBEcA+LDDh1NKj0ozBD4hw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ffe25428-890b-4aa3-839a-98584e473185",
                            TwoFactorEnabled = false,
                            UserName = "EveDavis"
                        },
                        new
                        {
                            Id = "e5c98b1e-5b93-4a7a-9b5a-7a9f9b7b9b7b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "231fa195-8e2a-4c68-abbb-c5838bd6ce40",
                            Email = "david@brown.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJO6qvf/OC2vzeFKrZV45JMEINXO3J+LjxNlii3HJX4l7V7ZaGvPZctXpkTbnBdYGA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "738b24d5-55cf-4bb1-805d-145277c33f5d",
                            TwoFactorEnabled = false,
                            UserName = "DavidBrown"
                        },
                        new
                        {
                            Id = "f6d87a2d-6c84-4b8f-a9e3-8e7a6f5b4c3d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6264756f-e16d-4dfc-9441-d5dc73fc0036",
                            Email = "olivia@taylor.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJpi6SnvPfsusFuM6UA52sumkgzpH+DVuST2gON31iICWQ2/LHB5a5s2Uh6/MNCccg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2fbcf049-65cb-4d7a-b13d-5959196cb746",
                            TwoFactorEnabled = false,
                            UserName = "OliviaTaylor"
                        },
                        new
                        {
                            Id = "g7e96c3e-7d95-4c9a-b0f4-9c8b7a5d3e2f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "f86e96f0-49fe-4e92-b3ba-237512dd1bf6",
                            Email = "james@wilson.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEAoSzmXP2obY+i4RKkefTUFp/VwQ4RVkxIvb9C/ZK9W1Scw3Rcouj58NTmbyLVAraA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "9e1f9928-dcd8-466b-8e88-d667d51de3f6",
                            TwoFactorEnabled = false,
                            UserName = "JamesWilson"
                        },
                        new
                        {
                            Id = "h8f05d4f-8e06-4d0b-a105-ad9c6b4e4d1a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "2e6cd818-3ad1-4c5c-91bd-0f28dc09604e",
                            Email = "sophia@moore.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBz13NiAJB6DOXJEsKmg67kbtxzyzqGFQpFmN2dIYQeOUnBk0mvQzxw5ZhUpdaKCiA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "a662e6c5-47e2-4761-9b14-362a265eca23",
                            TwoFactorEnabled = false,
                            UserName = "SophiaMoore"
                        },
                        new
                        {
                            Id = "i9g14e5g-9f17-4e1c-b216-be8d5a3c2b0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "7f5e70e7-ada5-4882-9e7f-778a95539d22",
                            Email = "william@anderson.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEOnQhhzbuHds2MsH2oT+hu3CuVAqmpQ++FxhfMnxMv958dP+eTlnOXqFRjD/ks15Rg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1a8f6b2d-a45b-4724-abdd-9b1dc1d16b96",
                            TwoFactorEnabled = false,
                            UserName = "WilliamAnderson"
                        },
                        new
                        {
                            Id = "j0h23f6h-0a28-4f2d-b327-cf9e4b2d1c0c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9f4283bc-38c9-4333-99ae-6a27d84ff680",
                            Email = "mia@thomas.com",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJtPkDdxbIBm/Z5gO8Ed6GB/isMfltfR8W+JTvvIN8M2JyYZEHIhFMHguluMJa6/7g==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "bebd033b-ed37-4266-9047-bf652a2a4d90",
                            TwoFactorEnabled = false,
                            UserName = "MiaThomas"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "e9b4c5a4-76c6-44b7-88fb-35a0228c9572"
                        },
                        new
                        {
                            UserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "e5c98b1e-5b93-4a7a-9b5a-7a9f9b7b9b7b",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "f6d87a2d-6c84-4b8f-a9e3-8e7a6f5b4c3d",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "g7e96c3e-7d95-4c9a-b0f4-9c8b7a5d3e2f",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "h8f05d4f-8e06-4d0b-a105-ad9c6b4e4d1a",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "i9g14e5g-9f17-4e1c-b216-be8d5a3c2b0b",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "j0h23f6h-0a28-4f2d-b327-cf9e4b2d1c0c",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PulsePitch.Models.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserOneId")
                        .HasColumnType("integer");

                    b.Property<int>("UserTwoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserOneId");

                    b.HasIndex("UserTwoId");

                    b.ToTable("ChatRoom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserOneId = 1,
                            UserTwoId = 2
                        },
                        new
                        {
                            Id = 2,
                            UserOneId = 3,
                            UserTwoId = 4
                        },
                        new
                        {
                            Id = 3,
                            UserOneId = 5,
                            UserTwoId = 6
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Practice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Film"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Meeting"
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.Formations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Formations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A standard 4-3-3 attacking formation",
                            Name = "4-3-3 Default",
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.MatchRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProposedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RecieverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("MatchRequest");
                });

            modelBuilder.Entity("PulsePitch.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatRoomId = 1,
                            Content = "Hey there!",
                            ReceiverId = 2,
                            SenderId = 1,
                            SentAt = new DateTime(2026, 2, 1, 1, 56, 56, 4, DateTimeKind.Utc).AddTicks(3580)
                        },
                        new
                        {
                            Id = 2,
                            ChatRoomId = 1,
                            Content = "Hey! Ready for practice?",
                            ReceiverId = 1,
                            SenderId = 2,
                            SentAt = new DateTime(2026, 2, 1, 1, 57, 56, 4, DateTimeKind.Utc).AddTicks(3739)
                        },
                        new
                        {
                            Id = 3,
                            ChatRoomId = 2,
                            Content = "Coach, what time is the game?",
                            ReceiverId = 4,
                            SenderId = 3,
                            SentAt = new DateTime(2026, 2, 1, 1, 56, 56, 4, DateTimeKind.Utc).AddTicks(3811)
                        },
                        new
                        {
                            Id = 4,
                            ChatRoomId = 2,
                            Content = "6 PM sharp. Be there early.",
                            ReceiverId = 3,
                            SenderId = 4,
                            SentAt = new DateTime(2026, 2, 1, 1, 58, 56, 4, DateTimeKind.Utc).AddTicks(3813)
                        },
                        new
                        {
                            Id = 5,
                            ChatRoomId = 3,
                            Content = "New message!",
                            ReceiverId = 6,
                            SenderId = 5,
                            SentAt = new DateTime(2026, 2, 1, 1, 56, 56, 4, DateTimeKind.Utc).AddTicks(3816)
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.PlayerTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RequestedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayerId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            PlayerId = 2,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 4,
                            PlayerId = 3,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            PlayerId = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            PlayerId = 5,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 7,
                            PlayerId = 5,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 8,
                            PlayerId = 6,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 9,
                            PlayerId = 7,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 10,
                            PlayerId = 8,
                            TeamId = 8
                        },
                        new
                        {
                            Id = 11,
                            PlayerId = 9,
                            TeamId = 9
                        },
                        new
                        {
                            Id = 12,
                            PlayerId = 10,
                            TeamId = 10
                        },
                        new
                        {
                            Id = 14,
                            PlayerId = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            PlayerId = 3,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 17,
                            PlayerId = 3,
                            TeamId = 6
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.PlayersInFormation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("FormationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("PlayersInFormation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FormationId = 1,
                            Note = "Player 1",
                            PositionId = 1,
                            X = 920.0,
                            Y = 344.0
                        },
                        new
                        {
                            Id = 2,
                            FormationId = 1,
                            Note = "Player 2",
                            PositionId = 2,
                            X = 800.0,
                            Y = 122.0
                        },
                        new
                        {
                            Id = 3,
                            FormationId = 1,
                            Note = "Player 3",
                            PositionId = 3,
                            X = 800.0,
                            Y = 200.0
                        },
                        new
                        {
                            Id = 4,
                            FormationId = 1,
                            Note = "Player 4",
                            PositionId = 4,
                            X = 800.0,
                            Y = 433.0
                        },
                        new
                        {
                            Id = 5,
                            FormationId = 1,
                            Note = "Player 5",
                            PositionId = 5,
                            X = 800.0,
                            Y = 511.0
                        },
                        new
                        {
                            Id = 6,
                            FormationId = 1,
                            Note = "Player 6",
                            PositionId = 6,
                            X = 400.0,
                            Y = 316.0
                        },
                        new
                        {
                            Id = 7,
                            FormationId = 1,
                            Note = "Player 7",
                            PositionId = 7,
                            X = 600.0,
                            Y = 161.0
                        },
                        new
                        {
                            Id = 8,
                            FormationId = 1,
                            Note = "Player 8",
                            PositionId = 8,
                            X = 600.0,
                            Y = 472.0
                        },
                        new
                        {
                            Id = 9,
                            FormationId = 1,
                            Note = "Player 9",
                            PositionId = 9,
                            X = 400.0,
                            Y = 83.0
                        },
                        new
                        {
                            Id = 10,
                            FormationId = 1,
                            Note = "Player 10",
                            PositionId = 10,
                            X = 350.0,
                            Y = 316.0
                        },
                        new
                        {
                            Id = 11,
                            FormationId = 1,
                            Note = "Player 11",
                            PositionId = 11,
                            X = 400.0,
                            Y = 650.0
                        },
                        new
                        {
                            Id = 12,
                            FormationId = 1,
                            Note = "Player 1",
                            PositionId = 12,
                            X = 65.0,
                            Y = 350.0
                        },
                        new
                        {
                            Id = 13,
                            FormationId = 1,
                            Note = "Player 2",
                            PositionId = 13,
                            X = 200.0,
                            Y = 511.0
                        },
                        new
                        {
                            Id = 14,
                            FormationId = 1,
                            Note = "Player 3",
                            PositionId = 14,
                            X = 200.0,
                            Y = 433.0
                        },
                        new
                        {
                            Id = 15,
                            FormationId = 1,
                            Note = "Player 4",
                            PositionId = 15,
                            X = 200.0,
                            Y = 300.0
                        },
                        new
                        {
                            Id = 16,
                            FormationId = 1,
                            Note = "Player 5",
                            PositionId = 16,
                            X = 200.0,
                            Y = 122.0
                        },
                        new
                        {
                            Id = 17,
                            FormationId = 1,
                            Note = "Player 6",
                            PositionId = 17,
                            X = 300.0,
                            Y = 316.0
                        },
                        new
                        {
                            Id = 18,
                            FormationId = 1,
                            Note = "Player 7",
                            PositionId = 18,
                            X = 400.0,
                            Y = 472.0
                        },
                        new
                        {
                            Id = 19,
                            FormationId = 1,
                            Note = "Player 8",
                            PositionId = 19,
                            X = 400.0,
                            Y = 161.0
                        },
                        new
                        {
                            Id = 20,
                            FormationId = 1,
                            Note = "Player 9",
                            PositionId = 20,
                            X = 600.0,
                            Y = 550.0
                        },
                        new
                        {
                            Id = 21,
                            FormationId = 1,
                            Note = "Player 10",
                            PositionId = 21,
                            X = 650.0,
                            Y = 316.0
                        },
                        new
                        {
                            Id = 22,
                            FormationId = 1,
                            Note = "Player 11",
                            PositionId = 22,
                            X = 600.0,
                            Y = 183.0
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("boolean");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RequiresApproval")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            IsPublic = false,
                            JoinCode = "EGL123",
                            Name = "Eagles",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 2,
                            CoachId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            IsPublic = false,
                            JoinCode = "FLC123",
                            Name = "Falcons",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 3,
                            CoachId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            IsPublic = false,
                            JoinCode = "WLV456",
                            Name = "Wolves",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 4,
                            CoachId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            IsPublic = false,
                            JoinCode = "SHK789",
                            Name = "Sharks",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 5,
                            CoachId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            IsPublic = false,
                            JoinCode = "TTN321",
                            Name = "Titans",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 6,
                            CoachId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            IsPublic = false,
                            JoinCode = "PNR654",
                            Name = "Panthers",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 7,
                            CoachId = "e5c98b1e-5b93-4a7a-9b5a-7a9f9b7b9b7b",
                            IsPublic = false,
                            JoinCode = "WAR789",
                            Name = "Warriors",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 8,
                            CoachId = "f6d87a2d-6c84-4b8f-a9e3-8e7a6f5b4c3d",
                            IsPublic = false,
                            JoinCode = "ROY321",
                            Name = "Royals",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 9,
                            CoachId = "g7e96c3e-7d95-4c9a-b0f4-9c8b7a5d3e2f",
                            IsPublic = false,
                            JoinCode = "STR654",
                            Name = "Stars",
                            RequiresApproval = false
                        },
                        new
                        {
                            Id = 10,
                            CoachId = "h8f05d4f-8e06-4d0b-a105-ad9c6b4e4d1a",
                            IsPublic = false,
                            JoinCode = "RNG987",
                            Name = "Rangers",
                            RequiresApproval = false
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.TeamEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Morning practice session",
                            End = new DateTime(2025, 6, 6, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Afternoon film",
                            End = new DateTime(2025, 6, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 6, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2,
                            Title = "film"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Early morning drills",
                            End = new DateTime(2025, 6, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 3,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 4,
                            Description = "team meeting",
                            End = new DateTime(2025, 6, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Start = new DateTime(2025, 6, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 4,
                            Title = "meeting"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tactical strategy session",
                            End = new DateTime(2025, 6, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 6, 9, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 5,
                            Title = "film"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Shooting practice",
                            End = new DateTime(2025, 6, 4, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 4, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 6,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ball control and drills",
                            End = new DateTime(2025, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Defensive coordination",
                            End = new DateTime(2025, 6, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Start = new DateTime(2025, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2,
                            Title = "meeting"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Midfield passing accuracy",
                            End = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 3,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Set-piece rehearsals",
                            End = new DateTime(2025, 6, 6, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 6, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 4,
                            Title = "film"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Evening conditioning session",
                            End = new DateTime(2025, 6, 12, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 5,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 12,
                            Description = "practice Championship Game",
                            End = new DateTime(2025, 6, 13, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 6,
                            Title = "practice"
                        },
                        new
                        {
                            Id = 13,
                            Description = "State Tournament prep",
                            End = new DateTime(2025, 6, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 6, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 7,
                            Title = "Tournament"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Morning practice session",
                            End = new DateTime(2025, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 8,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Morning practice session",
                            End = new DateTime(2025, 7, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 7, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Afternoon film",
                            End = new DateTime(2025, 7, 4, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 7, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2,
                            Title = "film"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Early morning drills",
                            End = new DateTime(2025, 7, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 7, 6, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 3,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 20,
                            Description = "team meeting",
                            End = new DateTime(2025, 7, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Start = new DateTime(2025, 7, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 4,
                            Title = "meeting"
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.TeamGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("OnCalendar")
                        .HasColumnType("boolean");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("TeamGames");

                    b.HasData(
                        new
                        {
                            Id = 19,
                            AwayTeamId = 4,
                            End = new DateTime(2025, 6, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 6, 10, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AwayTeamId = 2,
                            End = new DateTime(2025, 6, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            OnCalendar = true,
                            Result = "2-1",
                            Start = new DateTime(2025, 6, 10, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AwayTeamId = 5,
                            End = new DateTime(2025, 6, 23, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            OnCalendar = true,
                            Result = "3-2",
                            Start = new DateTime(2025, 6, 23, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AwayTeamId = 3,
                            End = new DateTime(2025, 6, 24, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 6,
                            OnCalendar = true,
                            Result = "1-0",
                            Start = new DateTime(2025, 6, 24, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1,
                            AwayTeamId = 1,
                            End = new DateTime(2025, 6, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 4,
                            OnCalendar = true,
                            Result = "2-2",
                            Start = new DateTime(2025, 6, 25, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 4,
                            End = new DateTime(2025, 6, 12, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            OnCalendar = true,
                            Result = "0-0",
                            Start = new DateTime(2025, 6, 12, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 6,
                            End = new DateTime(2025, 6, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 5,
                            OnCalendar = true,
                            Result = "1-3",
                            Start = new DateTime(2025, 6, 14, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AwayTeamId = 8,
                            End = new DateTime(2025, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            OnCalendar = true,
                            Result = "4-2",
                            Start = new DateTime(2025, 6, 15, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AwayTeamId = 1,
                            End = new DateTime(2025, 6, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 6,
                            OnCalendar = true,
                            Result = "1-1",
                            Start = new DateTime(2025, 6, 17, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AwayTeamId = 5,
                            End = new DateTime(2025, 6, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            OnCalendar = true,
                            Result = "0-2",
                            Start = new DateTime(2025, 6, 18, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AwayTeamId = 1,
                            End = new DateTime(2025, 6, 22, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 7,
                            OnCalendar = true,
                            Result = "3-3",
                            Start = new DateTime(2025, 6, 22, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AwayTeamId = 5,
                            End = new DateTime(2025, 6, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            OnCalendar = true,
                            Result = "1-0",
                            Start = new DateTime(2025, 6, 29, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AwayTeamId = 3,
                            End = new DateTime(2025, 6, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 6,
                            OnCalendar = true,
                            Result = "2-2",
                            Start = new DateTime(2025, 6, 28, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AwayTeamId = 2,
                            End = new DateTime(2025, 6, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 5,
                            OnCalendar = true,
                            Result = "3-1",
                            Start = new DateTime(2025, 6, 25, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AwayTeamId = 7,
                            End = new DateTime(2025, 7, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 7, 2, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AwayTeamId = 3,
                            End = new DateTime(2025, 7, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 6,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 7, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AwayTeamId = 4,
                            End = new DateTime(2025, 7, 8, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 7, 8, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AwayTeamId = 9,
                            End = new DateTime(2025, 7, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 5,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 7, 9, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<string>("ImageLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .HasColumnType("text[]");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateTime = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            ImageLocation = "https://robohash.org/numquamutut.png?size=150x150&set=set1",
                            LastName = "Strator"
                        },
                        new
                        {
                            Id = 2,
                            CreateDateTime = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            IdentityUserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            ImageLocation = "https://robohash.org/nisiautemet.png?size=150x150&set=set1",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            CreateDateTime = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            IdentityUserId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            ImageLocation = "https://robohash.org/molestiaemagnamet.png?size=150x150&set=set1",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            CreateDateTime = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            IdentityUserId = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            ImageLocation = "https://robohash.org/deseruntutipsum.png?size=150x150&set=set1",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 5,
                            CreateDateTime = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bob",
                            IdentityUserId = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            ImageLocation = "https://robohash.org/quiundedignissimos.png?size=150x150&set=set1",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 6,
                            CreateDateTime = new DateTime(2022, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eve",
                            IdentityUserId = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            ImageLocation = "https://robohash.org/hicnihilipsa.png?size=150x150&set=set1",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 7,
                            CreateDateTime = new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            IdentityUserId = "e5c98b1e-5b93-4a7a-9b5a-7a9f9b7b9b7b",
                            ImageLocation = "https://robohash.org/etvoluptatemquas.png?size=150x150&set=set1",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 8,
                            CreateDateTime = new DateTime(2023, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            IdentityUserId = "f6d87a2d-6c84-4b8f-a9e3-8e7a6f5b4c3d",
                            ImageLocation = "https://robohash.org/eiusdoloreea.png?size=150x150&set=set1",
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 9,
                            CreateDateTime = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            IdentityUserId = "g7e96c3e-7d95-4c9a-b0f4-9c8b7a5d3e2f",
                            ImageLocation = "https://robohash.org/voluptatemautemdolor.png?size=150x150&set=set1",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 10,
                            CreateDateTime = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            IdentityUserId = "h8f05d4f-8e06-4d0b-a105-ad9c6b4e4d1a",
                            ImageLocation = "https://robohash.org/quoslaboriosamodio.png?size=150x150&set=set1",
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 11,
                            CreateDateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            IdentityUserId = "i9g14e5g-9f17-4e1c-b216-be8d5a3c2b0b",
                            ImageLocation = "https://robohash.org/temporibusdoloreea.png?size=150x150&set=set1",
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 12,
                            CreateDateTime = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mia",
                            IdentityUserId = "j0h23f6h-0a28-4f2d-b327-cf9e4b2d1c0c",
                            ImageLocation = "https://robohash.org/rerumveritatisunde.png?size=150x150&set=set1",
                            LastName = "Thomas"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PulsePitch.Models.ChatRoom", b =>
                {
                    b.HasOne("PulsePitch.Models.UserProfile", "UserOne")
                        .WithMany()
                        .HasForeignKey("UserOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.UserProfile", "UserTwo")
                        .WithMany()
                        .HasForeignKey("UserTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserOne");

                    b.Navigation("UserTwo");
                });

            modelBuilder.Entity("PulsePitch.Models.Formations", b =>
                {
                    b.HasOne("PulsePitch.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PulsePitch.Models.MatchRequest", b =>
                {
                    b.HasOne("PulsePitch.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("PulsePitch.Models.Message", b =>
                {
                    b.HasOne("PulsePitch.Models.ChatRoom", "ChatRoom")
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.UserProfile", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.UserProfile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PulsePitch.Models.PlayerTeam", b =>
                {
                    b.HasOne("PulsePitch.Models.UserProfile", "Player")
                        .WithMany("Teams")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PulsePitch.Models.PlayersInFormation", b =>
                {
                    b.HasOne("PulsePitch.Models.Formations", "Formation")
                        .WithMany("Players")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("PulsePitch.Models.TeamEvent", b =>
                {
                    b.HasOne("PulsePitch.Models.Events", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PulsePitch.Models.TeamGame", b =>
                {
                    b.HasOne("PulsePitch.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("PulsePitch.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("PulsePitch.Models.Formations", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PulsePitch.Models.UserProfile", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
