// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PulsePitch.Data;

#nullable disable

namespace PulsePitchBackend.Migrations
{
    [DbContext(typeof(PulsePitchDbContext))]
    partial class PulsePitchDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f",
                            Name = "Player",
                            NormalizedName = "PLAYER"
                        },
                        new
                        {
                            Id = "e9b4c5a4-76c6-44b7-88fb-35a0228c9572",
                            Name = "Coach",
                            NormalizedName = "COACH"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9bc64793-0279-45ed-b029-16683809972c",
                            Email = "admina@strator.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEObraD+tHu7GKiJ4b6f32SbARkmCdF1GiS0SdmYVh72n+3YdVtxFjNh6EkExz7ZojA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "83c84709-5690-4e37-96c0-93c65438c08c",
                            TwoFactorEnabled = false,
                            UserName = "Administrator"
                        },
                        new
                        {
                            Id = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "1d7ef48f-5871-4294-9611-b2d8b888539e",
                            Email = "john@doe.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEH44t1LnPfv3Pbf7a4Wv7o7nNrsEAeF4we2c7f52p+R40juINkzuNOG7McDKZcMrBg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "8848d01c-630e-44f8-b38f-b6a741d582f1",
                            TwoFactorEnabled = false,
                            UserName = "JohnDoe"
                        },
                        new
                        {
                            Id = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "ae1a6312-9a9e-4bd1-9c53-11c9943281e6",
                            Email = "jane@smith.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKY7qiS45HvHirJonRdPSIkenhN3NqhxBnyx5Ayxco+g2jHoOfc1MDhw84i1i6oPAg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "1ca2fa93-c4fc-47b2-a812-670d914722e1",
                            TwoFactorEnabled = false,
                            UserName = "JaneSmith"
                        },
                        new
                        {
                            Id = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "94a29486-fba6-4fe7-b5bc-4b49c8976152",
                            Email = "alice@johnson.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEJqX+colBbeUDbHsX6CP1V09vB3u+Jnb1tuo+Q5e+hplfs9NBf4ms4ARMocRzvxLmQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "3dbe54d3-d995-4c10-a00e-e6e7dc43aadf",
                            TwoFactorEnabled = false,
                            UserName = "AliceJohnson"
                        },
                        new
                        {
                            Id = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "cceab545-a4f7-4f31-8b78-c6ea2fa072e6",
                            Email = "bob@williams.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEMx8kI4erY8kODbI7lCmKZmHdZR6aYaEM8fzFbR9uNgqUvop+7lKSSpPKh6NhUuSPA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "ee2425d4-f548-484f-a700-b8d0481a42ad",
                            TwoFactorEnabled = false,
                            UserName = "BobWilliams"
                        },
                        new
                        {
                            Id = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "aad06858-404a-4549-a66c-70fb7424ad3f",
                            Email = "Eve@Davis.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEGuu5KTkef6IMNolsREoBF5XNdAJ1esJ3LzZRi0ogjrmk3c6MEZaZ8sElgV2DfmK+w==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "5cbde0ec-8ef4-4161-8c6b-840851568704",
                            TwoFactorEnabled = false,
                            UserName = "EveDavis"
                        },
                        new
                        {
                            Id = "e5c98b1e-5b93-4a7a-9b5a-7a9f9b7b9b7b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "05269dc4-ed5a-4f1d-8102-d80b5567a633",
                            Email = "david@brown.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEDhzlXWvRW93q+X74qQNfkG3r+ZHIfaBLYepsMqnU82axGb58WDZkH3Mk+6HnzCfbQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2e98093a-2e1b-4227-9ba5-e1845e9a8b42",
                            TwoFactorEnabled = false,
                            UserName = "DavidBrown"
                        },
                        new
                        {
                            Id = "f6d87a2d-6c84-4b8f-a9e3-8e7a6f5b4c3d",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c6a9f715-7582-4c56-a171-57e588d7674c",
                            Email = "olivia@taylor.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEKT1SfsqM8csjfm7uGlQCBrdtKXr6H6hQzJJPzLOrS30uTZx/Tzu4p81E7ttbGCnKg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7bd642fc-cafd-4b02-a90e-9523185bcf5e",
                            TwoFactorEnabled = false,
                            UserName = "OliviaTaylor"
                        },
                        new
                        {
                            Id = "g7e96c3e-7d95-4c9a-b0f4-9c8b7a5d3e2f",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "dcea1a82-562c-49d8-8cee-897d6c4f2664",
                            Email = "james@wilson.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEF8tzSAKAYbAK0WdvBAK7OBTbGHBIUI5Hu3ajSeWEM8sRkSrDsTWC3kspvBd2/3qLg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "7151ccb0-b94b-420d-a4ee-fadc90944745",
                            TwoFactorEnabled = false,
                            UserName = "JamesWilson"
                        },
                        new
                        {
                            Id = "h8f05d4f-8e06-4d0b-a105-ad9c6b4e4d1a",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "bde41eed-dfb6-4911-8487-580e34c8481a",
                            Email = "sophia@moore.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEBClTyRS53ywVLJTIQ4X7iMOvEk3FyRnDVDUIJLi4+ijfImpAGtgwDf8ptvNHIxjqQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f6e1484b-b978-42af-ada0-0c33e1ab5144",
                            TwoFactorEnabled = false,
                            UserName = "SophiaMoore"
                        },
                        new
                        {
                            Id = "i9g14e5g-9f17-4e1c-b216-be8d5a3c2b0b",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d77c1918-8e6b-4dae-b9ed-a510241ee9b1",
                            Email = "william@anderson.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEHQGQ/gnAP8eF3hmzYODk4WF6bI14oYXx/q1FQKX1zzbb+dj2GWMP3BmY+1VV9M4ew==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "04a9ac98-d22a-42f6-bb12-90d93be974b7",
                            TwoFactorEnabled = false,
                            UserName = "WilliamAnderson"
                        },
                        new
                        {
                            Id = "j0h23f6h-0a28-4f2d-b327-cf9e4b2d1c0c",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "3d0bda85-a1af-4f4d-9f4a-63b15961b523",
                            Email = "mia@thomas.comx",
                            EmailConfirmed = false,
                            LockoutEnabled = false,
                            PasswordHash = "AQAAAAIAAYagAAAAEPsjIANe+tyy816Q8K+YqUA0zINOigztfWNiYWECDFchPLL7Ih49ikcZVTz+s3heIQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "fc25ee1e-94d6-4a4a-ba99-3419c13e77d1",
                            TwoFactorEnabled = false,
                            UserName = "MiaThomas"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            RoleId = "e9b4c5a4-76c6-44b7-88fb-35a0228c9572"
                        },
                        new
                        {
                            UserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "e5c98b1e-5b93-4a7a-9b5a-7a9f9b7b9b7b",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "f6d87a2d-6c84-4b8f-a9e3-8e7a6f5b4c3d",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "g7e96c3e-7d95-4c9a-b0f4-9c8b7a5d3e2f",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "h8f05d4f-8e06-4d0b-a105-ad9c6b4e4d1a",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "i9g14e5g-9f17-4e1c-b216-be8d5a3c2b0b",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "j0h23f6h-0a28-4f2d-b327-cf9e4b2d1c0c",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        },
                        new
                        {
                            UserId = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            RoleId = "cb1c88d2-f3be-4c6b-b31f-a5f3e39e274f"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("PulsePitch.Models.ChatRoom", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("UserOneId")
                        .HasColumnType("integer");

                    b.Property<int>("UserTwoId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UserOneId");

                    b.HasIndex("UserTwoId");

                    b.ToTable("ChatRoom");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            UserOneId = 1,
                            UserTwoId = 2
                        },
                        new
                        {
                            Id = 2,
                            UserOneId = 3,
                            UserTwoId = 4
                        },
                        new
                        {
                            Id = 3,
                            UserOneId = 5,
                            UserTwoId = 6
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.Events", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Practice"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Film"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Meeting"
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.Formations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.ToTable("Formations");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A standard 4-3-3 attacking formation",
                            Name = "4-3-3 Default",
                            TeamId = 1
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.MatchRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .HasColumnType("text");

                    b.Property<DateTime>("ProposedDate")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("RecieverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("MatchRequest");
                });

            modelBuilder.Entity("PulsePitch.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ChatRoomId")
                        .HasColumnType("integer");

                    b.Property<string>("Content")
                        .HasColumnType("text");

                    b.Property<int>("ReceiverId")
                        .HasColumnType("integer");

                    b.Property<int>("SenderId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("ChatRoomId");

                    b.HasIndex("ReceiverId");

                    b.HasIndex("SenderId");

                    b.ToTable("Messages");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChatRoomId = 1,
                            Content = "Hey there!",
                            ReceiverId = 2,
                            SenderId = 1,
                            SentAt = new DateTime(2025, 11, 18, 4, 15, 50, 645, DateTimeKind.Utc).AddTicks(4413)
                        },
                        new
                        {
                            Id = 2,
                            ChatRoomId = 1,
                            Content = "Hey! Ready for practice?",
                            ReceiverId = 1,
                            SenderId = 2,
                            SentAt = new DateTime(2025, 11, 18, 4, 16, 50, 645, DateTimeKind.Utc).AddTicks(4503)
                        },
                        new
                        {
                            Id = 3,
                            ChatRoomId = 2,
                            Content = "Coach, what time is the game?",
                            ReceiverId = 4,
                            SenderId = 3,
                            SentAt = new DateTime(2025, 11, 18, 4, 15, 50, 645, DateTimeKind.Utc).AddTicks(4545)
                        },
                        new
                        {
                            Id = 4,
                            ChatRoomId = 2,
                            Content = "6 PM sharp. Be there early.",
                            ReceiverId = 3,
                            SenderId = 4,
                            SentAt = new DateTime(2025, 11, 18, 4, 17, 50, 645, DateTimeKind.Utc).AddTicks(4546)
                        },
                        new
                        {
                            Id = 5,
                            ChatRoomId = 3,
                            Content = "New message!",
                            ReceiverId = 6,
                            SenderId = 5,
                            SentAt = new DateTime(2025, 11, 18, 4, 15, 50, 645, DateTimeKind.Utc).AddTicks(4547)
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.PlayerTeam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("PlayerId")
                        .HasColumnType("integer");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("PlayerTeams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            PlayerId = 1,
                            TeamId = 1
                        },
                        new
                        {
                            Id = 2,
                            PlayerId = 2,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 4,
                            PlayerId = 3,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 5,
                            PlayerId = 4,
                            TeamId = 3
                        },
                        new
                        {
                            Id = 6,
                            PlayerId = 5,
                            TeamId = 4
                        },
                        new
                        {
                            Id = 7,
                            PlayerId = 5,
                            TeamId = 6
                        },
                        new
                        {
                            Id = 8,
                            PlayerId = 6,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 9,
                            PlayerId = 7,
                            TeamId = 7
                        },
                        new
                        {
                            Id = 10,
                            PlayerId = 8,
                            TeamId = 8
                        },
                        new
                        {
                            Id = 11,
                            PlayerId = 9,
                            TeamId = 9
                        },
                        new
                        {
                            Id = 12,
                            PlayerId = 10,
                            TeamId = 10
                        },
                        new
                        {
                            Id = 14,
                            PlayerId = 2,
                            TeamId = 2
                        },
                        new
                        {
                            Id = 16,
                            PlayerId = 3,
                            TeamId = 5
                        },
                        new
                        {
                            Id = 17,
                            PlayerId = 3,
                            TeamId = 6
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.PlayersInFormation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<int>("FormationId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Note")
                        .HasColumnType("text");

                    b.Property<int>("PositionId")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.ToTable("PlayersInFormation");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FormationId = 1,
                            Note = "Player 1",
                            PositionId = 1,
                            X = 920.0,
                            Y = 344.0
                        },
                        new
                        {
                            Id = 2,
                            FormationId = 1,
                            Note = "Player 2",
                            PositionId = 2,
                            X = 800.0,
                            Y = 122.0
                        },
                        new
                        {
                            Id = 3,
                            FormationId = 1,
                            Note = "Player 3",
                            PositionId = 3,
                            X = 800.0,
                            Y = 200.0
                        },
                        new
                        {
                            Id = 4,
                            FormationId = 1,
                            Note = "Player 4",
                            PositionId = 4,
                            X = 800.0,
                            Y = 433.0
                        },
                        new
                        {
                            Id = 5,
                            FormationId = 1,
                            Note = "Player 5",
                            PositionId = 5,
                            X = 800.0,
                            Y = 511.0
                        },
                        new
                        {
                            Id = 6,
                            FormationId = 1,
                            Note = "Player 6",
                            PositionId = 6,
                            X = 400.0,
                            Y = 316.0
                        },
                        new
                        {
                            Id = 7,
                            FormationId = 1,
                            Note = "Player 7",
                            PositionId = 7,
                            X = 600.0,
                            Y = 161.0
                        },
                        new
                        {
                            Id = 8,
                            FormationId = 1,
                            Note = "Player 8",
                            PositionId = 8,
                            X = 600.0,
                            Y = 472.0
                        },
                        new
                        {
                            Id = 9,
                            FormationId = 1,
                            Note = "Player 9",
                            PositionId = 9,
                            X = 400.0,
                            Y = 83.0
                        },
                        new
                        {
                            Id = 10,
                            FormationId = 1,
                            Note = "Player 10",
                            PositionId = 10,
                            X = 350.0,
                            Y = 316.0
                        },
                        new
                        {
                            Id = 11,
                            FormationId = 1,
                            Note = "Player 11",
                            PositionId = 11,
                            X = 400.0,
                            Y = 650.0
                        },
                        new
                        {
                            Id = 12,
                            FormationId = 1,
                            Note = "Player 1",
                            PositionId = 12,
                            X = 65.0,
                            Y = 350.0
                        },
                        new
                        {
                            Id = 13,
                            FormationId = 1,
                            Note = "Player 2",
                            PositionId = 13,
                            X = 200.0,
                            Y = 511.0
                        },
                        new
                        {
                            Id = 14,
                            FormationId = 1,
                            Note = "Player 3",
                            PositionId = 14,
                            X = 200.0,
                            Y = 433.0
                        },
                        new
                        {
                            Id = 15,
                            FormationId = 1,
                            Note = "Player 4",
                            PositionId = 15,
                            X = 200.0,
                            Y = 300.0
                        },
                        new
                        {
                            Id = 16,
                            FormationId = 1,
                            Note = "Player 5",
                            PositionId = 16,
                            X = 200.0,
                            Y = 122.0
                        },
                        new
                        {
                            Id = 17,
                            FormationId = 1,
                            Note = "Player 6",
                            PositionId = 17,
                            X = 300.0,
                            Y = 316.0
                        },
                        new
                        {
                            Id = 18,
                            FormationId = 1,
                            Note = "Player 7",
                            PositionId = 18,
                            X = 400.0,
                            Y = 472.0
                        },
                        new
                        {
                            Id = 19,
                            FormationId = 1,
                            Note = "Player 8",
                            PositionId = 19,
                            X = 400.0,
                            Y = 161.0
                        },
                        new
                        {
                            Id = 20,
                            FormationId = 1,
                            Note = "Player 9",
                            PositionId = 20,
                            X = 600.0,
                            Y = 550.0
                        },
                        new
                        {
                            Id = 21,
                            FormationId = 1,
                            Note = "Player 10",
                            PositionId = 21,
                            X = 650.0,
                            Y = 316.0
                        },
                        new
                        {
                            Id = 22,
                            FormationId = 1,
                            Note = "Player 11",
                            PositionId = 22,
                            X = 600.0,
                            Y = 183.0
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CoachId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("JoinCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Teams");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CoachId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            JoinCode = "EGL123",
                            Name = "Eagles"
                        },
                        new
                        {
                            Id = 2,
                            CoachId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            JoinCode = "FLC123",
                            Name = "Falcons"
                        },
                        new
                        {
                            Id = 3,
                            CoachId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            JoinCode = "WLV456",
                            Name = "Wolves"
                        },
                        new
                        {
                            Id = 4,
                            CoachId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            JoinCode = "SHK789",
                            Name = "Sharks"
                        },
                        new
                        {
                            Id = 5,
                            CoachId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            JoinCode = "TTN321",
                            Name = "Titans"
                        },
                        new
                        {
                            Id = 6,
                            CoachId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            JoinCode = "PNR654",
                            Name = "Panthers"
                        },
                        new
                        {
                            Id = 7,
                            CoachId = "e5c98b1e-5b93-4a7a-9b5a-7a9f9b7b9b7b",
                            JoinCode = "WAR789",
                            Name = "Warriors"
                        },
                        new
                        {
                            Id = 8,
                            CoachId = "f6d87a2d-6c84-4b8f-a9e3-8e7a6f5b4c3d",
                            JoinCode = "ROY321",
                            Name = "Royals"
                        },
                        new
                        {
                            Id = 9,
                            CoachId = "g7e96c3e-7d95-4c9a-b0f4-9c8b7a5d3e2f",
                            JoinCode = "STR654",
                            Name = "Stars"
                        },
                        new
                        {
                            Id = 10,
                            CoachId = "h8f05d4f-8e06-4d0b-a105-ad9c6b4e4d1a",
                            JoinCode = "RNG987",
                            Name = "Rangers"
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.TeamEvent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("EventId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("TeamId")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamEvents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Morning practice session",
                            End = new DateTime(2025, 6, 6, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Afternoon film",
                            End = new DateTime(2025, 6, 10, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 6, 10, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2,
                            Title = "film"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Early morning drills",
                            End = new DateTime(2025, 6, 5, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 5, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 3,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 4,
                            Description = "team meeting",
                            End = new DateTime(2025, 6, 8, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Start = new DateTime(2025, 6, 8, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 4,
                            Title = "meeting"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Tactical strategy session",
                            End = new DateTime(2025, 6, 9, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 6, 9, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 5,
                            Title = "film"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Shooting practice",
                            End = new DateTime(2025, 6, 4, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 4, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 6,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Ball control and drills",
                            End = new DateTime(2025, 6, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 3, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Defensive coordination",
                            End = new DateTime(2025, 6, 11, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Start = new DateTime(2025, 6, 11, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2,
                            Title = "meeting"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Midfield passing accuracy",
                            End = new DateTime(2025, 6, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 3,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Set-piece rehearsals",
                            End = new DateTime(2025, 6, 6, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 6, 6, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 4,
                            Title = "film"
                        },
                        new
                        {
                            Id = 11,
                            Description = "Evening conditioning session",
                            End = new DateTime(2025, 6, 12, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 12, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 5,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 12,
                            Description = "practice Championship Game",
                            End = new DateTime(2025, 6, 13, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 6, 13, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 6,
                            Title = "practice"
                        },
                        new
                        {
                            Id = 13,
                            Description = "State Tournament prep",
                            End = new DateTime(2025, 6, 15, 22, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 6, 14, 8, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 7,
                            Title = "Tournament"
                        },
                        new
                        {
                            Id = 14,
                            Description = "Morning practice session",
                            End = new DateTime(2025, 7, 1, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 7, 1, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 8,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 17,
                            Description = "Morning practice session",
                            End = new DateTime(2025, 7, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 7, 3, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 1,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 18,
                            Description = "Afternoon film",
                            End = new DateTime(2025, 7, 4, 16, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 2,
                            Start = new DateTime(2025, 7, 4, 14, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 2,
                            Title = "film"
                        },
                        new
                        {
                            Id = 19,
                            Description = "Early morning drills",
                            End = new DateTime(2025, 7, 6, 9, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 1,
                            Start = new DateTime(2025, 7, 6, 7, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 3,
                            Title = "Practice"
                        },
                        new
                        {
                            Id = 20,
                            Description = "team meeting",
                            End = new DateTime(2025, 7, 7, 12, 0, 0, 0, DateTimeKind.Unspecified),
                            EventId = 3,
                            Start = new DateTime(2025, 7, 7, 10, 0, 0, 0, DateTimeKind.Unspecified),
                            TeamId = 4,
                            Title = "meeting"
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.TeamGame", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AwayTeamId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("End")
                        .HasColumnType("timestamp without time zone");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("integer");

                    b.Property<bool>("OnCalendar")
                        .HasColumnType("boolean");

                    b.Property<string>("Result")
                        .HasColumnType("text");

                    b.Property<DateTime>("Start")
                        .HasColumnType("timestamp without time zone");

                    b.HasKey("Id");

                    b.HasIndex("AwayTeamId");

                    b.HasIndex("HomeTeamId");

                    b.ToTable("TeamGames");

                    b.HasData(
                        new
                        {
                            Id = 19,
                            AwayTeamId = 4,
                            End = new DateTime(2025, 6, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 6, 10, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            AwayTeamId = 2,
                            End = new DateTime(2025, 6, 10, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            OnCalendar = true,
                            Result = "2-1",
                            Start = new DateTime(2025, 6, 10, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            AwayTeamId = 5,
                            End = new DateTime(2025, 6, 23, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            OnCalendar = true,
                            Result = "3-2",
                            Start = new DateTime(2025, 6, 23, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            AwayTeamId = 3,
                            End = new DateTime(2025, 6, 24, 21, 30, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 6,
                            OnCalendar = true,
                            Result = "1-0",
                            Start = new DateTime(2025, 6, 24, 20, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 1,
                            AwayTeamId = 1,
                            End = new DateTime(2025, 6, 25, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 4,
                            OnCalendar = true,
                            Result = "2-2",
                            Start = new DateTime(2025, 6, 25, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            AwayTeamId = 4,
                            End = new DateTime(2025, 6, 12, 18, 30, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            OnCalendar = true,
                            Result = "0-0",
                            Start = new DateTime(2025, 6, 12, 17, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            AwayTeamId = 6,
                            End = new DateTime(2025, 6, 14, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 5,
                            OnCalendar = true,
                            Result = "1-3",
                            Start = new DateTime(2025, 6, 14, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            AwayTeamId = 8,
                            End = new DateTime(2025, 6, 15, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            OnCalendar = true,
                            Result = "4-2",
                            Start = new DateTime(2025, 6, 15, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            AwayTeamId = 1,
                            End = new DateTime(2025, 6, 17, 17, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 6,
                            OnCalendar = true,
                            Result = "1-1",
                            Start = new DateTime(2025, 6, 17, 16, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            AwayTeamId = 5,
                            End = new DateTime(2025, 6, 18, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 3,
                            OnCalendar = true,
                            Result = "0-2",
                            Start = new DateTime(2025, 6, 18, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            AwayTeamId = 1,
                            End = new DateTime(2025, 6, 22, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 7,
                            OnCalendar = true,
                            Result = "3-3",
                            Start = new DateTime(2025, 6, 22, 18, 30, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            AwayTeamId = 5,
                            End = new DateTime(2025, 6, 29, 18, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            OnCalendar = true,
                            Result = "1-0",
                            Start = new DateTime(2025, 6, 29, 17, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            AwayTeamId = 3,
                            End = new DateTime(2025, 6, 28, 21, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 6,
                            OnCalendar = true,
                            Result = "2-2",
                            Start = new DateTime(2025, 6, 28, 20, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            AwayTeamId = 2,
                            End = new DateTime(2025, 6, 25, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 5,
                            OnCalendar = true,
                            Result = "3-1",
                            Start = new DateTime(2025, 6, 25, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            AwayTeamId = 7,
                            End = new DateTime(2025, 7, 2, 20, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 1,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 7, 2, 19, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            AwayTeamId = 3,
                            End = new DateTime(2025, 7, 5, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 6,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 7, 5, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            AwayTeamId = 4,
                            End = new DateTime(2025, 7, 8, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 2,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 7, 8, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            AwayTeamId = 9,
                            End = new DateTime(2025, 7, 9, 19, 0, 0, 0, DateTimeKind.Unspecified),
                            HomeTeamId = 5,
                            OnCalendar = true,
                            Result = "TBD",
                            Start = new DateTime(2025, 7, 9, 18, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("PulsePitch.Models.UserProfile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("IdentityUserId")
                        .HasColumnType("text");

                    b.Property<string>("ImageLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.PrimitiveCollection<List<string>>("Roles")
                        .HasColumnType("text[]");

                    b.Property<string>("UserName")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IdentityUserId");

                    b.ToTable("UserProfiles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateDateTime = new DateTime(2022, 1, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Admina",
                            IdentityUserId = "dbc40bc6-0829-4ac5-a3ed-180f5e916a5f",
                            ImageLocation = "https://robohash.org/numquamutut.png?size=150x150&set=set1",
                            LastName = "Strator"
                        },
                        new
                        {
                            Id = 2,
                            CreateDateTime = new DateTime(2023, 2, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "John",
                            IdentityUserId = "d8d76512-74f1-43bb-b1fd-87d3a8aa36df",
                            ImageLocation = "https://robohash.org/nisiautemet.png?size=150x150&set=set1",
                            LastName = "Doe"
                        },
                        new
                        {
                            Id = 3,
                            CreateDateTime = new DateTime(2022, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Jane",
                            IdentityUserId = "a7d21fac-3b21-454a-a747-075f072d0cf3",
                            ImageLocation = "https://robohash.org/molestiaemagnamet.png?size=150x150&set=set1",
                            LastName = "Smith"
                        },
                        new
                        {
                            Id = 4,
                            CreateDateTime = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Alice",
                            IdentityUserId = "c806cfae-bda9-47c5-8473-dd52fd056a9b",
                            ImageLocation = "https://robohash.org/deseruntutipsum.png?size=150x150&set=set1",
                            LastName = "Johnson"
                        },
                        new
                        {
                            Id = 5,
                            CreateDateTime = new DateTime(2023, 5, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Bob",
                            IdentityUserId = "9ce89d88-75da-4a80-9b0d-3fe58582b8e2",
                            ImageLocation = "https://robohash.org/quiundedignissimos.png?size=150x150&set=set1",
                            LastName = "Williams"
                        },
                        new
                        {
                            Id = 6,
                            CreateDateTime = new DateTime(2022, 10, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Eve",
                            IdentityUserId = "d224a03d-bf0c-4a05-b728-e3521e45d74d",
                            ImageLocation = "https://robohash.org/hicnihilipsa.png?size=150x150&set=set1",
                            LastName = "Davis"
                        },
                        new
                        {
                            Id = 7,
                            CreateDateTime = new DateTime(2024, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "David",
                            IdentityUserId = "e5c98b1e-5b93-4a7a-9b5a-7a9f9b7b9b7b",
                            ImageLocation = "https://robohash.org/etvoluptatemquas.png?size=150x150&set=set1",
                            LastName = "Brown"
                        },
                        new
                        {
                            Id = 8,
                            CreateDateTime = new DateTime(2023, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Olivia",
                            IdentityUserId = "f6d87a2d-6c84-4b8f-a9e3-8e7a6f5b4c3d",
                            ImageLocation = "https://robohash.org/eiusdoloreea.png?size=150x150&set=set1",
                            LastName = "Taylor"
                        },
                        new
                        {
                            Id = 9,
                            CreateDateTime = new DateTime(2022, 9, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "James",
                            IdentityUserId = "g7e96c3e-7d95-4c9a-b0f4-9c8b7a5d3e2f",
                            ImageLocation = "https://robohash.org/voluptatemautemdolor.png?size=150x150&set=set1",
                            LastName = "Wilson"
                        },
                        new
                        {
                            Id = 10,
                            CreateDateTime = new DateTime(2024, 10, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Sophia",
                            IdentityUserId = "h8f05d4f-8e06-4d0b-a105-ad9c6b4e4d1a",
                            ImageLocation = "https://robohash.org/quoslaboriosamodio.png?size=150x150&set=set1",
                            LastName = "Moore"
                        },
                        new
                        {
                            Id = 11,
                            CreateDateTime = new DateTime(2023, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "William",
                            IdentityUserId = "i9g14e5g-9f17-4e1c-b216-be8d5a3c2b0b",
                            ImageLocation = "https://robohash.org/temporibusdoloreea.png?size=150x150&set=set1",
                            LastName = "Anderson"
                        },
                        new
                        {
                            Id = 12,
                            CreateDateTime = new DateTime(2022, 12, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FirstName = "Mia",
                            IdentityUserId = "j0h23f6h-0a28-4f2d-b327-cf9e4b2d1c0c",
                            ImageLocation = "https://robohash.org/rerumveritatisunde.png?size=150x150&set=set1",
                            LastName = "Thomas"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("PulsePitch.Models.ChatRoom", b =>
                {
                    b.HasOne("PulsePitch.Models.UserProfile", "UserOne")
                        .WithMany()
                        .HasForeignKey("UserOneId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.UserProfile", "UserTwo")
                        .WithMany()
                        .HasForeignKey("UserTwoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserOne");

                    b.Navigation("UserTwo");
                });

            modelBuilder.Entity("PulsePitch.Models.Formations", b =>
                {
                    b.HasOne("PulsePitch.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PulsePitch.Models.MatchRequest", b =>
                {
                    b.HasOne("PulsePitch.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("PulsePitch.Models.Message", b =>
                {
                    b.HasOne("PulsePitch.Models.ChatRoom", "ChatRoom")
                        .WithMany()
                        .HasForeignKey("ChatRoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.UserProfile", "Receiver")
                        .WithMany()
                        .HasForeignKey("ReceiverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.UserProfile", "Sender")
                        .WithMany()
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChatRoom");

                    b.Navigation("Receiver");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("PulsePitch.Models.PlayerTeam", b =>
                {
                    b.HasOne("PulsePitch.Models.UserProfile", "Player")
                        .WithMany("Teams")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PulsePitch.Models.PlayersInFormation", b =>
                {
                    b.HasOne("PulsePitch.Models.Formations", "Formation")
                        .WithMany("Players")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("PulsePitch.Models.TeamEvent", b =>
                {
                    b.HasOne("PulsePitch.Models.Events", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("PulsePitch.Models.TeamGame", b =>
                {
                    b.HasOne("PulsePitch.Models.Team", "AwayTeam")
                        .WithMany()
                        .HasForeignKey("AwayTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PulsePitch.Models.Team", "HomeTeam")
                        .WithMany()
                        .HasForeignKey("HomeTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AwayTeam");

                    b.Navigation("HomeTeam");
                });

            modelBuilder.Entity("PulsePitch.Models.UserProfile", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", "IdentityUser")
                        .WithMany()
                        .HasForeignKey("IdentityUserId");

                    b.Navigation("IdentityUser");
                });

            modelBuilder.Entity("PulsePitch.Models.Formations", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("PulsePitch.Models.UserProfile", b =>
                {
                    b.Navigation("Teams");
                });
#pragma warning restore 612, 618
        }
    }
}
